name: Compile Executable

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: KamaranL/Ahk2Exe-action@v1
        with:
          in: ./src/index.ahk
          out: ./PowerToys.Run.WindowsKey.exe

      - uses: actions/upload-artifact@v4
        with:
          name: PowerToys.Run.WindowsKey
          path: ./PowerToys.Run.WindowsKey.exe
